name: Deploy ExchangesHealthCheck Function App
on:
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: exchangeshealthcheck
  AZURE_FUNCTIONAPP_PACKAGE_PATH: HelperServices\ExchangesHealthCheck.Functions\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  SOLUTION: TradingBots.sln
  SERVICE_DIRECTORY: HelperServices\ExchangesHealthCheck.Functions

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: dotnet restore "${{ env.SERVICE_DIRECTORY }}"

    - name: Build
      run: dotnet build "${{ env.SERVICE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test "${{ env.SOLUTION }}" --configuration ${{ env.CONFIGURATION }} --no-build --no-restore

    - name: Publish
      run: dotnet publish "${{ env.SERVICE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        include-hidden-files: true

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.exchangeshealthcheck_A87C }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
